# Generated by Django 4.0.3 on 2022-06-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tunnel_ipv4', models.GenericIPAddressField()),
                ('tunnel_ipv6', models.GenericIPAddressField()),
                ('public_key', models.CharField(max_length=44)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
