# Generated by Django 4.0.4 on 2022-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_peer_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
