# Generated by Django 4.0.4 on 2022-09-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_peer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='psk',
            field=models.CharField(blank=True, default=None, max_length=44, null=True),
        ),
    ]
